=== dcyjukxm/slickedit/sc_04030200_multi_full/plugins/com.slickedit.windows.libs_4.3.2/slickedit/sysconfig/coolfeatures/coolfeatures.dtd
<?xml encoding='UTF-8'?>
<!ELEMENT CoolFeatures (TagLines, Features) >
  <!ATTLIST CoolFeatures Version (11.0|11.0.1|12.0|13.0.0) #REQUIRED>
<!ELEMENT TagLines (TagLine)*>
<!ELEMENT TagLine (#PCDATA)>
<!ELEMENT Features (Feature)*>
<!ELEMENT Feature (#PCDATA)>
  <!ATTLIST Feature Name CDATA #REQUIRED>
  <!ATTLIST Feature Products CDATA #IMPLIED>
  <!ATTLIST Feature Configure CDATA #IMPLIED>
  <!ATTLIST Feature HelpTopic CDATA #IMPLIED>
  <!ATTLIST Feature DemoURL CDATA #IMPLIED>
  <!ATTLIST Feature PDemoURL CDATA #IMPLIED>
  <!ATTLIST Feature New CDATA #IMPLIED>

=== dcyjukxm/slickedit/sc_04030200_multi_full/plugins/com.slickedit.windows.libs_4.3.2/slickedit/sysconfig/coolfeatures/coolfeatures.xml
<!DOCTYPE CoolFeatures SYSTEM "coolfeatures.dtd">
<CoolFeatures Version="13.0.0">
  <TagLines>
    <!--
         There can be more than one marketing tag line;
         a different one will come up each time.
    -->
    <TagLine>
At SlickEdit we believe that there is only one thing
cooler than our software&amp;mdash;&lt;em&gt;the developers who use it.&lt;/em&gt;
To get the most out of SlickEdit&amp;reg;, check out these
cool features.
    </TagLine>
  </TagLines>
  <Features>
    <Feature Name="Code Navigation"
             Configure="showCoolFeaturesOptions C/C++ &gt; Context Tagging®"
             HelpTopic="symbol navigation"
             DemoURL="http://www.slickedit.com/demo/high/CodeNavigation/CodeNavigation.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/CodeNavigation/CodeNavigation.html">
Use Ctrl+Dot to jump from a symbol to its definition.
Use Ctrl+/ to list all of the references for the
current symbol and optionally jump to the first
reference.  These operations set a bookmark that can be
popped to return you to the previous location (Ctrl+Comma).
    </Feature>
    <Feature Name="Preview Tool Window"
             Configure=""
             HelpTopic="Preview tool window"
             DemoURL="http://www.slickedit.com/demo/high/PreviewToolWindow/PreviewToolWindow.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/PreviewToolWindow/PreviewToolWindow.html">
Displays the definition of the current symbol and associated
documentation in the editor window, allowing you to see the
definition without having to open a separate buffer.  The Preview
window also shows information for other windows, including
the Class, Defs, References, and Symbols tool windows. By default,
Preview is docked into a tab group along the bottom of the editor.
It can also be displayed by selecting &lt;b&gt;View > Toolbars > Preview&lt;/b&gt;.
    </Feature>
    <Feature Name="References Tool Window"
             Configure="showCoolFeaturesOptions Context Tagging®"
             HelpTopic="References view"
             DemoURL="http://www.slickedit.com/demo/high/ReferencesView/ReferencesView.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/ReferencesView/ReferencesView.html">
Displays the list of references for a symbol.  Use
Ctrl+/ to open the References window for the current
symbol, or you can type or select a symbol in the
&lt;b&gt;Symbol&lt;/b&gt; drop-down list.  Click on a reference to preview
it.  Double-click to jump to it. By default,
the References window is docked into a tab group along the bottom of the editor.
It can also be displayed by selecting &lt;b&gt;View > Toolbars > References&lt;/b&gt;.
    </Feature>
    <Feature Name="Syntax Expansion"
             Configure="setupext -indent"
             HelpTopic="syntax expansion"
             DemoURL="http://www.slickedit.com/demo/high/SyntaxExpansion/SyntaxExpansion.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/SyntaxExpansion/SyntaxExpansion.html">
Expands common block structures (&lt;i&gt;if&lt;/i&gt;, &lt;i&gt;for&lt;/i&gt;, &lt;i&gt;try&lt;/i&gt;, etc.)
when the initial keyword is typed. For example, when
"if" is typed followed by a space, SlickEdit inserts
the parentheses for the condition and the braces. You
can define additional structures to be expanded.
    </Feature>
    <Feature Name="Dynamic Surround and Surround With"
             Configure="setupext -indent"
             HelpTopic="surrounding text"
             DemoURL="http://www.slickedit.com/demo/high/SurroundWith/SurroundWith.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/SurroundWith/SurroundWith.html">
Surround existing lines of code with block statements
or tags. Dynamic Surround allows you to expand a block
after syntax expansion, using the arrow keys to move the
end of the block up or down. Surround With allows you to
select lines and then choose a block structure or tag.
    </Feature>
    <Feature Name="Auto-Completions"
             Configure="setupext -autocomplete"
             HelpTopic="Auto-Complete"
             DemoURL="http://www.slickedit.com/demo/high/AutoCompletions/AutoCompletions.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/AutoCompletions/AutoCompletions.html">
Completions reduce keystrokes by automatically
completing symbols as you type.  After typing the first
few characters of a symbol, a brief pause will pop up a
list of possible completions.  This list is comprised
of matching symbols in the tag database and matching
lines of code in the current buffer.  If a line match
is selected you can add successively more text from
that line using the &lt;b&gt;complete-more&lt;/b&gt; command
(Ctrl+Shift+Space).
    </Feature>
    <Feature Name="Editable, Dynamic Differencing (DIFFzilla&amp;reg;)"
             Configure="diff-options"
             HelpTopic="DIFFzilla"
             DemoURL="http://www.slickedit.com/demo/high/DIFFzilla/DIFFzilla.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/DIFFzilla/DIFFzilla.html">
Use to compare directories and files.  When comparing
files, the diff highlights the lines and characters
that do not match.  You can edit the files in the
diff view using many of the features available in the
editor window.  The diff is automatically updated as
you edit.
    </Feature>
    <Feature Name="Code Templates"
             Configure="template-manager"
             HelpTopic="Code Templates"
             DemoURL="http://www.slickedit.com/demo/high/CodeTemplates/CodeTemplates.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/CodeTemplates/CodeTemplates.html">
Define templates for commonly used code, like
standard class definitions or design patterns.  You can
create templates for whole files or multiple files.
Add a template item to your current project by choosing
&lt;b&gt;File > New Item from Template&lt;/b&gt; from the main menu.
You are prompted for values to substitute in the new instance as needed.
    </Feature>
    <Feature Name="Aliases"
             Configure="showCoolFeaturesOptions Global Aliases"
             HelpTopic="aliases"
             DemoURL="http://www.slickedit.com/demo/high/Aliases/Aliases.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/Aliases/Aliases.html">
Define short names that can be expanded to
insert text into a file or directory path in SlickEdit,
using Ctrl+Space.  Aliases can automatically insert the
date, time, cursor placement, or prompt for parameters.
    </Feature>
    <Feature Name="Comment Wrapping"
             Configure="setupext -commentwrap"
             HelpTopic="comment wrapping"
             DemoURL="http://www.slickedit.com/demo/high/CommentWrapping/CommentWrapping.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/CommentWrapping/CommentWrapping.html">
Formats block comments as you edit them, automatically
wrapping based on your settings. Comment wrapping
preserves comment border characters.
    </Feature>
    <Feature Name="XML/HTML Formatting"
             Configure="xml_html_options3"
             HelpTopic="xml/html formatting"
             DemoURL="http://www.slickedit.com/demo/high/XMLHTMLFormatting/XMLHTMLFormatting.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/XMLHTMLFormatting/XMLHTMLFormatting.html">
Content in XML and HTML files may be set to automatically
      wrap and format as you edit according to user-defined formatting schemes. A formatting
      scheme is comprised of any number of XML or HTML tags, each of which can be configured
      individually for indent levels, wrapping, and tag structure. Multiple schemes can be
      defined—for example, you may want one scheme for HTML files and another for XML files,
      or perhaps you are required to code certain files to various standards. Schemes can be
      saved and imported, so they can be shared with your team. Tags for each scheme can be
      entered manually or you can import tags from the current file.
    </Feature>
    <Feature Name="Backup History"
             Configure="showCoolFeaturesOptions Backup"
             HelpTopic="Backup History"
             DemoURL="http://www.slickedit.com/demo/high/BackupHistory/BackupHistory.html"
             Products="SlickEdit,Tools">
Each time a file is saved, the current version is added
to the Backup History.  You can view the list of
versions and compare the current version against a
previous version or restore a previous version.  This
creates a detailed history for versions
that are not ready to be checked in.
    </Feature>
    <Feature Name="Smart Line Selections"
             Configure="showCoolFeaturesOptions Editing &gt; General"
             HelpTopic="Line insert style"
             DemoURL="http://www.slickedit.com/demo/high/SmartLineSelections/SmartLineSelections.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/SmartLineSelections/SmartLineSelections.html">
Line selections for single or multiple lines are pasted
above or below the current line of code (depending upon your
&lt;b&gt;Line insert style&lt;/b&gt; setting), saving you from tediously
positioning the cursor at the beginning or end of a
line prior to pasting the selected lines.
    </Feature>
    <Feature Name="SmartPaste&amp;reg;"
             Configure="setupext -indent"
             HelpTopic="SmartPaste"
             DemoURL="http://www.slickedit.com/demo/high/SmartPaste/SmartPaste.html"
             PDemoURL="http://www.slickedit.com/demo-c/high/SmartPaste/SmartPaste.html">
Automatically formats line selections when pasted. The pasted
code is formatted to match the indentation of the new location
and the brace style adjusted to match your settings.
    </Feature>
    <Feature Name="Syntax-Driven Searching"
