=== dcyjukxm/slickedit/sc_04030200_multi_full/plugins/com.slickedit.linux.libs_4.3.2/slickedit/sysconfig/gnucopts.dtd
<?xml encoding='UTF-8'?>
<!ELEMENT GNUCOptions (OptionSet)*>
  <!ATTLIST GNUCOptions Version (8.0) #REQUIRED>
  <!ATTLIST GNUCOptions GCCVersion CDATA #REQUIRED>
<!ELEMENT OptionSet (Option)*>
  <!ATTLIST OptionSet Type CDATA #REQUIRED>
  <!ATTLIST OptionSet Architecture CDATA #IMPLIED>
<!ELEMENT Option EMPTY>
  <!ATTLIST Option Name CDATA #REQUIRED>
  <!ATTLIST Option Description CDATA #REQUIRED>

=== dcyjukxm/slickedit/sc_04030200_multi_full/plugins/com.slickedit.windows.libs_4.3.2/slickedit/sysconfig/gnucopts.xml
<!DOCTYPE GNUCOptions SYSTEM "gnucopts.dtd">

<!-- NOTE: The options that are commented out are either configurable via a control elsewhere in the
           dialog, are handled automatically (ex: -c, -I, -l), or they require more
           information than a simple checkbox (ex: -Wid-clash-LEN where LEN is a number) -->

<GNUCOptions Version="8.0" GCCVersion="2.96">
	<OptionSet Type="Warning">
		<!-- Option Name="-fsyntax-only" Description="Check the code for syntax errors, but don't do anything beyond that."/ -->
		<!-- Option Name="-pedantic" Description="Issue all the warnings demanded by strict ISO C/C++."/ -->
		<Option Name="-pedantic-errors" Description="Like -pedantic, but errors are produced instead of warnings."/>
		<!-- Option Name="-w" Description="Inhibit all warning messages"/ -->
		<Option Name="-W" Description="Print extra warning messages for several events."/>
		<Option Name="-Waggregate-return" Description="Warn if any functions that return structures or unions are defined or called."/>
		<!-- Option Name="-Wall" Description="All of the typical '-W' options combined. (-Wimplicit-int -Wimplicit-function-declaration -Wimplicit -Wmain -Wreturn-type -Wunused-function -Wunused-label -Wunused-parameter -Wunused-variable -Wunused-value -Wunused -Wswitch -Wcomment -Wtrigraphs -Wformat -Wchar-subscripts -Wuninitialized -Wparentheses)"/ -->
		<Option Name="-Wbad-function-cast" Description="Warn whenever a function call is cast to a non-matching type."/>
		<Option Name="-Wcast-align" Description="Warn whenever a pointer is cast such that the required alignment of the target is increased."/>
		<Option Name="-Wcast-qual" Description="Warn whenever a pointer is cast so as to remove a type qualifier from the target type."/>
		<Option Name="-Wchar-subscripts" Description="Warn if an array subscript has type 'char'"/>
		<Option Name="-Wcomment" Description="Warn whenever a comment-start sequence '/*' appears in a '/*' comment, or whenever a backslash-newline appears in a '//' comment."/>
		<Option Name="-Wconversion" Description="Warn if a prototype causes a type conversion that is different from what would happen to the same argument in the absence of a prototype."/>
		<!-- Option Name="-Werror" Description="Make all warnings into errors."/ -->
		<Option Name="-Werror-implicit-function-declaration" Description="Give an error whenever a function is used before being declared."/>
		<Option Name="-Wfloat-equal" Description="Warn if floating point values are used in equality comparisons."/>
		<Option Name="-Wformat" Description="Check calls to 'printf' and 'scanf', etc., to make sure that the arguments supplied have the appropriate types."/>
		<!-- Option Name="-Wid-clash-LEN" Description="Warn whenever two distinct identifiers match in the first LEN characters."/ -->
		<Option Name="-Wimplicit-int" Description="Warn when a declaration does not specify a type."/>
		<Option Name="-Wimplicit-function-declaration" Description="Give a warning whenever a function is used before being declared."/>
		<Option Name="-Wimplicit" Description="Same as '-Wimplicit-int' and '-Wimplicit-function-declaration'."/>
		<Option Name="-Winline" Description="Warn if a function can not be inlined and it was declared as inline."/>
		<!-- Option Name="-Wlarger-than-LEN" Description="Warn whenever an object of larger than LEN bytes is defined."/ -->
		<Option Name="-Wlong-long" Description="Warn if 'long long' type is used."/>
		<Option Name="-Wmain" Description="Warn if the type of 'main' is suspicious."/>
		<Option Name="-Wmissing-declarations" Description="Warn if a global function is defined without a previous declaration."/>
		<Option Name="-Wmissing-noreturn" Description="Warn about functions which might be candidates for attribute 'noreturn'."/>
		<Option Name="-Wmissing-prototypes" Description="Warn if a global function is defined without a previous prototype declaration."/>
		<Option Name="-Wmultichar" Description="Warn if a multicharacter constant is used."/>
		<Option Name="-Wnested-externs" Description="Warn if an 'extern' declaration is encountered within a function."/>
		<Option Name="-Wno-import" Description="Inhibit warning messages about the use of 'import'"/>
		<Option Name="-Wpacked" Description="Warn if a structure is given the packed attribute, but the packed attribute has no effect on the layout or size of the structure."/>
		<Option Name="-Wpadded" Description="Warn if padding is included in a structure, either to align an element of the structure or to align the whole structure."/>
		<Option Name="-Wparentheses" Description="Warn if parentheses are omitted in certain contexts."/>
		<Option Name="-Wpointer-arith" Description="Warn about anything that depends on the 'size of' a function type or of 'void'."/>
		<Option Name="-Wredundant-decls" Description="Warn if anything is declared more than once in the same scope."/>
		<Option Name="-Wreorder" Description="Warn when the order of member initializers given in the code does not match the order in which they must be executed."/>
		<Option Name="-Wreturn-type" Description="Warn whenever a function is defined with a return-type that defaults to 'int'.  Also warn about non-void functions that have no return value."/>
		<Option Name="-Wshadow" Description="Warn whenever a local variable shadows another local variable, parameter, or global variable."/>
		<Option Name="-Wsign-compare" Description="Warn when a comparison between signed and unsigned values could produce an incorrect result when the signed value is converted to unsigned."/>
		<Option Name="-Wstrict-prototypes" Description="Warn if a function is declared or defined without specifying the argument types."/>
		<Option Name="-Wswitch" Description="Warn whenever a 'switch' statement has an index of enumeral type and lacks a 'case' for one or more of the named codes of that enumeration."/>
		<Option Name="-Wtraditional" Description="Warn about certain constructs that behave differently in traditional and ANSI C."/>
		<Option Name="-Wtrigraphs" Description="Warn if any trigraphs are encountered."/>
		<Option Name="-Wundef" Description="Warn if an undefined identifier is evaluated in an '#if' directive."/>
		<Option Name="-Wunreachable-code" Description="Warn if the compiler detects that code will never be executed."/>
		<Option Name="-Wunused-function" Description="Warn whenever a static function is declared but not defined or a non-inline static function is unused."/>
		<Option Name="-Wunused-label" Description="Warn whenever a label is declared buy not used."/>
		<Option Name="-Wunused-parameter" Description="Warn whenever a function parameter is unused aside from its declaration."/>
		<Option Name="-Wunused-variable" Description="Warn whenever a local variable or non-constant static variable is unused aside from its declaration."/>
		<Option Name="-Wunused-value" Description="Warn whenever a statement computes a result that is explicitly not used."/>
		<Option Name="-Wunused" Description="All the above '-Wunused' options combined."/>
		<Option Name="-Wuninitialized" Description="Warn if an automatic variable is used without first being initialized."/>
		<Option Name="-Wunknown-pragmas" Description="Warn when a #pragma directive is encountered which is not understood by GCC."/>
		<Option Name="-Wwrite-strings" Description="Give string constants the type 'const char[LENGTH]' so that copying the address of one into a non-'const' 'char *' will get a warning."/>
	</OptionSet>

	<OptionSet Type="Overall">
		<!-- Option Name="-x language" Description="Specify explicitly the language for the following input files."/ -->
		<Option Name="-x none" Description="Turn off any specification of a language, so that subsequent files are handled according to their file name suffixes."/>
		<!-- Option Name="-c" Description="Compile or assemble the source files, but do not link. The compiler output is an object file corresponding to each source file."/ -->
		<Option Name="-S" Description="Stop after the stage of compilation proper; do not assemble. The output is an assembler code file for each non-assembler input file specified."/>
		<Option Name="-E" Description="Stop after the preprocessing stage; do not run the compiler proper. The output is preprocessed source code, which is sent to the standard output."/>
		<!-- Option Name="-o file" Description="Place output in file file. This applies regardless to whatever sort of output GCC is producing."/ -->
		<!-- Option Name="-v" Description="Print (on standard error output) the commands executed to run the stages of compilation."/ -->
		<!-- Option Name="-pipe" Description="Use pipes rather than temporary files for communication between the various stages of compilation."/ -->
	</OptionSet>

	<OptionSet Type="Language">
		<!-- Option Name="-ansi" Description="Support all ANSI standard C programs."/ -->
		<Option Name="-fno-asm" Description="Do not recognize asm, inline or typeof as a keyword. These words may then be used as identifiers."/>
		<Option Name="-fno-builtin" Description="Don't recognize built-in functions that do not begin with two leading underscores."/>
		<Option Name="-fhosted" Description="Compile for a hosted environment; this implies the `-fbuiltin' option, and implies that suspicious declarations of main should be warned about."/>
		<Option Name="-ffreestanding" Description="Compile for a freestanding environment; this implies the `-fno-builtin' option, and implies that main has no special requirements."/>
		<Option Name="-fno-strict-prototype" Description="Treat a function declaration with no arguments, such as `int foo ();', as C would treat it."/>
		<Option Name="-trigraphs" Description="Support ANSI C trigraphs. The `-ansi' option implies `-trigraphs'."/>
		<!-- Option Name="-traditional" Description="Attempt to support some aspects of traditional C compilers."/ -->
